# .yamllint.yaml
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start:
    present: true
    level: warning
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore: |
  node_modules/
  .git/