apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: fashion-kafka-minimal
  namespace: fashion-analytics
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.9"
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 250m
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
