apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-generator
  template:
    metadata:
      labels:
        app: data-generator
    spec:
      containers:
        - name: data-generator
          image: kafka-producer:latest  # local docker registry
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
