apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fashion-orders
  namespace: fashion-analytics
  labels:
    strimzi.io/cluster: fashion-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824 # 1 GB
