apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: fashion-products
  namespace: fashion-analytics
  labels:
    strimzi.io/cluster: fashion-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 2592000000 # 30 days
    segment.bytes: 1073741824 # 1 GB