apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml 

helmCharts:
  - name: strimzi-kafka-operator
    repo: https://strimzi.io/charts/
    version: 0.45.0
    releaseName: strimzi-kafka-operator
    namespace: kafka-operator
    valuesFile: values.yaml