apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-external
  namespace: fashion-analytics
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: flink
    component: jobmanager