# kafka-cluster.yaml
# Corrected production-grade Kafka configuration
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: fashion-kafka
  namespace: fashion-analytics
spec:
  kafka:
    version: 3.9.0  # Ensure this is a supported version
    replicas: 3  # Production-grade redundancy with 3 brokers
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30092
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.9"
      # Memory optimization settings
      log.cleaner.threads: 1
      num.io.threads: 4
      num.network.threads: 3
      num.replica.fetchers: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    jvmOptions:
      -Xms: "512m"
      -Xmx: "512m"
    storage:
      # Using persistent storage with moderate size
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
      class: standard
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3  # Production-grade ZooKeeper ensemble
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 250m
    jvmOptions:
      -Xms: "256m"
      -Xmx: "256m"
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
      class: standard
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: 
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m