# kafka-cluster.yaml
# Corrected production-grade Kafka configuration
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: fashion-kafka
  namespace: fashion-analytics
spec:
  kafka:
    version: 3.9.0
    replicas: 1 # Production-grade redundancy would have 3 brokers
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30093
            host: 127.0.0.1
    config:
      offsets.topic.replication.factor: 1 # use 3 for prod
      transaction.state.log.replication.factor: 1 # use 3 for prod
      transaction.state.log.min.isr: 1 # use 2 for prod
      default.replication.factor: 1 #use 3 for prod
      min.insync.replicas: 1 # use 2 for prod
      inter.broker.protocol.version: "3.9"
      # Memory optimization settings
      log.cleaner.threads: 1
      num.io.threads: 4
      num.network.threads: 3
      num.replica.fetchers: 1
      message.max.bytes: 200000000  # Increase message size
      replica.fetch.max.bytes: 200000000  # Allow larger fetches
      listener.security.protocol.map: "EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      listeners: "PLAINTEXT://:9092,EXTERNAL://:9094"
      advertised.listeners: "PLAINTEXT://my-cluster-kafka-bootstrap.default.svc.cluster.local:9092,EXTERNAL://127.0.0.1:30093"
      inter.broker.listener.name: PLAINTEXT
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    jvmOptions:
      -Xms: "512m"
      -Xmx: "512m"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: standard
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1 # Production-grade ZooKeeper ensemble would be 3
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 250m
    jvmOptions:
      -Xms: "256m"
      -Xmx: "256m"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: standard
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
    userOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
