apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio-registry-instance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kieDotson/fashion-analytics-processor.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/apicurio
    directory:
      recurse: true
      jsonnet: {}
      include: "registry.yaml"  # Only include the registry.yaml file
      exclude: "kustomization.yaml"  # Explicitly exclude the kustomization file
  destination:
    server: https://kubernetes.default.svc
    namespace: fashion-analytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true