apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio-registry-instance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kieDotson/fashion-analytics-processor.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/apicurio
    directory:
      recurse: true
      jsonnet: {}
      exclude: "kustomization.yaml"  # Skip kustomization processing
  destination:
    server: https://kubernetes.default.svc
    namespace: fashion-analytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m