apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurio-registry-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kieDotson/fashion-analytics-processor.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/operators/apicurio
  destination:
    server: https://kubernetes.default.svc
    namespace: fashion-analytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---

