apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-classes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/fashion-analytics-processor.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true