apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: fashion-registry
  namespace: fashion-analytics
spec:
  configuration:
    persistence: "kafkasql"
    kafkasql:
      bootstrapServers: "fashion-kafka-kafka-bootstrap.fashion-analytics.svc:9092"
  deployment:
    replicas: 1