kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
    extraMounts:
      - hostPath: /Users/k_book/Code/fashion-analytics-processor/infrastructure/kubernetes/kind-storage
        containerPath: /mnt/data
  - role: worker
    extraMounts:
      - hostPath: /Users/k_book/Code/fashion-analytics-processor/infrastructure/kubernetes/kind-storage
        containerPath: /mnt/data
  - role: worker
    extraMounts:
      - hostPath: /Users/k_book/Code/fashion-analytics-processor/infrastructure/kubernetes/kind-storage
        containerPath: /mnt/data