# .github/workflows/infrastructure.yaml
name: Infrastructure CI/CD

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/**"
  pull_request:
    branches: [main]
    paths:
      - "infrastructure/**"
  workflow_dispatch:
    # Allow manual triggers

env:
  KUBECTL_VERSION: "v1.28.0"
  KUSTOMIZE_VERSION: "v5.6.0"
  HELM_VERSION: "v3.12.1"

jobs:
  validate:
    name: Validate Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes tools
        run: |
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

          # Install kustomize directly from GitHub releases
          curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.6.0/kustomize_v5.6.0_linux_amd64.tar.gz -o kustomize.tar.gz
          tar -zxvf kustomize.tar.gz
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

          # Verify installation
          kustomize version

          # Install Helm
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh --version ${{ env.HELM_VERSION }}

          # Install yamllint
          sudo apt-get update && sudo apt-get install -y yamllint

      - name: Validate YAML formatting
        run: |
          # Create .yamllint.yaml file
          cat > $GITHUB_WORKSPACE/.yamllint.yaml << EOF
          extends: default

          rules:
            line-length:
              max: 120
              level: warning
            document-start:
              present: false
              level: warning
          EOF

          # Run yamllint with the newly created config
          yamllint -c $GITHUB_WORKSPACE/.yamllint.yaml infrastructure/

      - name: Validate Kustomize resources
        run: |
          # Initialize error flag
          KUSTOMIZE_ERROR=0

          # Validate each component using kustomize
          for dir in $(find infrastructure/kubernetes -name "kustomization.yaml" -exec dirname {} \;); do
            echo "Validating kustomize directory: $dir"
            if ! kustomize build $dir > /dev/null; then
              echo "Error: Kustomize validation failed in $dir"
              KUSTOMIZE_ERROR=1
            fi
          done

          # Exit with error if any kustomize build failed
          exit $KUSTOMIZE_ERROR

      - name: Add production Helm repositories
        run: |
          helm repo add strimzi https://strimzi.io/charts/
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
      
      - name: Validate Helm configurations
        run: |
          # Validate Strimzi values
          helm template --dry-run strimzi-kafka strimzi/strimzi-kafka-operator -f $GITHUB_WORKSPACE/infrastructure/kubernetes/strimzi/values.yaml
          
          # Validate Prometheus values
          helm template --dry-run prometheus prometheus-community/kube-prometheus-stack -f $GITHUB_WORKSPACE/infrastructure/kubernetes/monitoring/prometheus-values.yaml
      
      - name: Basic schema validation
        run: |
          # Install Kubeconform
          curl -L https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz -o kubeconform.tar.gz
          tar -zxvf kubeconform.tar.gz
          chmod +x kubeconform
          sudo mv kubeconform /usr/local/bin/
          kubeconform -ignore-missing-schemas -summary rendered-templates/*.yaml
          
      - name: Create ephemeral Kind cluster for server-side validation
        uses: helm/kind-action@v1.5.0
        
      - name: Install operator CRDs
        run: |
          kubectl apply -f https://strimzi.io/install/latest?namespace=default
          # Apply other CRDs
          
      - name: Advanced server-side validation
        run: |
          # we need special validation for custom controllers as kubeconform only handles core kubernetes components
          kubectl apply --dry-run=server -f rendered-templates/*.yaml


      - name: Check for syntax errors
        run: |
          # Initialize error flag
          SYNTAX_ERROR=0

          for file in $(find infrastructure -name "*.yaml" -type f -not -path "*/kustomization.yaml" -not -path "*/values.yaml"); do
            if ! kubectl apply --dry-run=client -f $file; then
              echo "Error: Syntax error in $file"
              SYNTAX_ERROR=1
            fi
          done

          # Exit with error if any syntax check failed
          exit $SYNTAX_ERROR
